//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { schema as $schema, type SchemaType as $Schema } from "./schema-lite";
import { type ModelResult as $ModelResult, type TypeDefResult as $TypeDefResult } from "@zenstackhq/orm";
export type TodoList = $ModelResult<$Schema, "TodoList">;
export type PostingPeriod = $ModelResult<$Schema, "PostingPeriod">;
export type Todo = $ModelResult<$Schema, "Todo">;
export type User = $ModelResult<$Schema, "User">;
export type Account = $ModelResult<$Schema, "Account">;
export type Verification = $ModelResult<$Schema, "Verification">;
export type Organization = $ModelResult<$Schema, "Organization">;
export type Team = $ModelResult<$Schema, "Team">;
export type Member = $ModelResult<$Schema, "Member">;
export type TeamMember = $ModelResult<$Schema, "TeamMember">;
export type Invitation = $ModelResult<$Schema, "Invitation">;
export type Session = $ModelResult<$Schema, "Session">;
export type ISOCountry = $ModelResult<$Schema, "ISOCountry">;
export type AddressRegion = $ModelResult<$Schema, "AddressRegion">;
export type Address = $ModelResult<$Schema, "Address">;
export type Apikey = $ModelResult<$Schema, "Apikey">;
export type GlAccount = $ModelResult<$Schema, "GlAccount">;
export type Partner = $ModelResult<$Schema, "Partner">;
export type ArAPPartner = $ModelResult<$Schema, "ArAPPartner">;
export type FiscalPeriodRule = $ModelResult<$Schema, "FiscalPeriodRule">;
export type Parameter = $ModelResult<$Schema, "Parameter">;
export type Company = $ModelResult<$Schema, "Company">;
export type CompanyPostingPeriod = $ModelResult<$Schema, "CompanyPostingPeriod">;
export type Fund = $ModelResult<$Schema, "Fund">;
export type GeneralFund = $ModelResult<$Schema, "GeneralFund">;
export type RestrictedFund = $ModelResult<$Schema, "RestrictedFund">;
export type DesignatedFund = $ModelResult<$Schema, "DesignatedFund">;
export type EndownmentPermanent = $ModelResult<$Schema, "EndownmentPermanent">;
export type EndownmentIncome = $ModelResult<$Schema, "EndownmentIncome">;
export type FundBalance = $ModelResult<$Schema, "FundBalance">;
export type JournalDoc = $ModelResult<$Schema, "JournalDoc">;
/**
 * Shape of the `auth()` function
 */
export type Auth = $TypeDefResult<$Schema, "Auth">;
export const Role = $schema.enums.Role.values;
export type Role = (typeof Role)[keyof typeof Role];
export const OrgLegalForm = $schema.enums.OrgLegalForm.values;
export type OrgLegalForm = (typeof OrgLegalForm)[keyof typeof OrgLegalForm];
export const OrgIdentificationType = $schema.enums.OrgIdentificationType.values;
export type OrgIdentificationType = (typeof OrgIdentificationType)[keyof typeof OrgIdentificationType];
export const OrgPlanType = $schema.enums.OrgPlanType.values;
export type OrgPlanType = (typeof OrgPlanType)[keyof typeof OrgPlanType];
export const PersonType = $schema.enums.PersonType.values;
export type PersonType = (typeof PersonType)[keyof typeof PersonType];
