//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, ExpressionUtils } from "@zenstackhq/orm/schema";
export class SchemaType implements SchemaDef {
    provider = {
        type: "postgresql",
        defaultSchema: "charitatis"
    } as const;
    models = {
        TodoList: {
            name: "TodoList",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    default: ExpressionUtils.call("cuid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true
                },
                name: {
                    name: "name",
                    type: "String"
                },
                owner: {
                    name: "owner",
                    type: "User",
                    relation: { opposite: "todoLists", fields: ["ownerId"], references: ["id"], onDelete: "Cascade", hasDefault: true }
                },
                ownerId: {
                    name: "ownerId",
                    type: "String",
                    default: ExpressionUtils.member(ExpressionUtils.call("auth"), ["userId"]),
                    foreignKeyFor: [
                        "owner"
                    ]
                },
                organization: {
                    name: "organization",
                    type: "Organization",
                    optional: true,
                    relation: { opposite: "todoLists", fields: ["organizationId"], references: ["id"], onDelete: "Cascade", hasDefault: true }
                },
                organizationId: {
                    name: "organizationId",
                    type: "String",
                    optional: true,
                    default: ExpressionUtils.member(ExpressionUtils.call("auth"), ["organizationId"]),
                    foreignKeyFor: [
                        "organization"
                    ]
                },
                todos: {
                    name: "todos",
                    type: "Todo",
                    array: true,
                    relation: { opposite: "list" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        PostingPeriod: {
            name: "PostingPeriod",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                year: {
                    name: "year",
                    type: "Int"
                },
                period: {
                    name: "period",
                    type: "Int"
                },
                open: {
                    name: "open",
                    type: "Boolean"
                },
                postPeriod: {
                    name: "postPeriod",
                    type: "CompanyPostingPeriod",
                    array: true,
                    relation: { opposite: "postPeriod" }
                },
                organization: {
                    name: "organization",
                    type: "Organization",
                    optional: true,
                    relation: { opposite: "postingPeriods", fields: ["organizationId"], references: ["id"], onDelete: "Cascade", hasDefault: true }
                },
                organizationId: {
                    name: "organizationId",
                    type: "String",
                    optional: true,
                    default: ExpressionUtils.member(ExpressionUtils.call("auth"), ["organizationId"]),
                    foreignKeyFor: [
                        "organization"
                    ]
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" }
            }
        },
        Todo: {
            name: "Todo",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    default: ExpressionUtils.call("cuid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true
                },
                title: {
                    name: "title",
                    type: "String"
                },
                done: {
                    name: "done",
                    type: "Boolean",
                    default: false
                },
                listId: {
                    name: "listId",
                    type: "String",
                    foreignKeyFor: [
                        "list"
                    ]
                },
                list: {
                    name: "list",
                    type: "TodoList",
                    relation: { opposite: "todos", fields: ["listId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        User: {
            name: "User",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    default: ExpressionUtils.call("cuid")
                },
                name: {
                    name: "name",
                    type: "String",
                    default: ""
                },
                displayName: {
                    name: "displayName",
                    type: "String",
                    default: ""
                },
                firstName: {
                    name: "firstName",
                    type: "String",
                    default: ""
                },
                familyName: {
                    name: "familyName",
                    type: "String",
                    default: ""
                },
                email: {
                    name: "email",
                    type: "String",
                    unique: true
                },
                emailVerified: {
                    name: "emailVerified",
                    type: "Boolean",
                    default: false
                },
                image: {
                    name: "image",
                    type: "String",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    default: ExpressionUtils.call("now")
                },
                role: {
                    name: "role",
                    type: "Role",
                    default: "user"
                },
                banned: {
                    name: "banned",
                    type: "Boolean",
                    optional: true
                },
                banReason: {
                    name: "banReason",
                    type: "String",
                    optional: true
                },
                banExpires: {
                    name: "banExpires",
                    type: "DateTime",
                    optional: true
                },
                sessions: {
                    name: "sessions",
                    type: "Session",
                    array: true,
                    relation: { opposite: "user" }
                },
                accounts: {
                    name: "accounts",
                    type: "Account",
                    array: true,
                    relation: { opposite: "user" }
                },
                members: {
                    name: "members",
                    type: "Member",
                    array: true,
                    relation: { opposite: "user" }
                },
                teamMembers: {
                    name: "teamMembers",
                    type: "TeamMember",
                    array: true,
                    relation: { opposite: "user" }
                },
                invitations: {
                    name: "invitations",
                    type: "Invitation",
                    array: true,
                    relation: { opposite: "user" }
                },
                todoLists: {
                    name: "todoLists",
                    type: "TodoList",
                    array: true,
                    relation: { opposite: "owner" }
                },
                apiKey: {
                    name: "apiKey",
                    type: "Apikey",
                    optional: true,
                    relation: { opposite: "user" }
                },
                glaccounts: {
                    name: "glaccounts",
                    type: "GlAccount",
                    array: true,
                    relation: { opposite: "createdBy" }
                },
                partners: {
                    name: "partners",
                    type: "Partner",
                    array: true,
                    relation: { opposite: "createdBy" }
                },
                funds: {
                    name: "funds",
                    type: "Fund",
                    array: true,
                    relation: { opposite: "createdBy" }
                },
                designatedFund: {
                    name: "designatedFund",
                    type: "DesignatedFund",
                    array: true,
                    relation: { opposite: "designatedBy", name: "designatedBy" }
                },
                createdDesignatedFund: {
                    name: "createdDesignatedFund",
                    type: "DesignatedFund",
                    array: true,
                    relation: { opposite: "designationCreatedBy", name: "designationCreate" }
                },
                releasedDesignatedFund: {
                    name: "releasedDesignatedFund",
                    type: "DesignatedFund",
                    array: true,
                    relation: { opposite: "designationReleasedBy", name: "designationRelease" }
                },
                lastLoginMethod: {
                    name: "lastLoginMethod",
                    type: "String",
                    optional: true
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                email: { type: "String" }
            }
        },
        Account: {
            name: "Account",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true
                },
                accountId: {
                    name: "accountId",
                    type: "String"
                },
                providerId: {
                    name: "providerId",
                    type: "String"
                },
                userId: {
                    name: "userId",
                    type: "String",
                    foreignKeyFor: [
                        "user"
                    ]
                },
                user: {
                    name: "user",
                    type: "User",
                    relation: { opposite: "accounts", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                },
                accessToken: {
                    name: "accessToken",
                    type: "String",
                    optional: true
                },
                refreshToken: {
                    name: "refreshToken",
                    type: "String",
                    optional: true
                },
                idToken: {
                    name: "idToken",
                    type: "String",
                    optional: true
                },
                accessTokenExpiresAt: {
                    name: "accessTokenExpiresAt",
                    type: "DateTime",
                    optional: true
                },
                refreshTokenExpiresAt: {
                    name: "refreshTokenExpiresAt",
                    type: "DateTime",
                    optional: true
                },
                scope: {
                    name: "scope",
                    type: "String",
                    optional: true
                },
                password: {
                    name: "password",
                    type: "String",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Verification: {
            name: "Verification",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true
                },
                identifier: {
                    name: "identifier",
                    type: "String"
                },
                value: {
                    name: "value",
                    type: "String"
                },
                expiresAt: {
                    name: "expiresAt",
                    type: "DateTime"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    optional: true,
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    optional: true,
                    updatedAt: true,
                    default: ExpressionUtils.call("now")
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Organization: {
            name: "Organization",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true
                },
                name: {
                    name: "name",
                    type: "String"
                },
                slug: {
                    name: "slug",
                    type: "String",
                    unique: true
                },
                logo: {
                    name: "logo",
                    type: "String",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime"
                },
                metadata: {
                    name: "metadata",
                    type: "String",
                    optional: true
                },
                tradingName: {
                    name: "tradingName",
                    type: "String"
                },
                legalForm: {
                    name: "legalForm",
                    type: "OrgLegalForm",
                    default: "SoleTrader"
                },
                legalName: {
                    name: "legalName",
                    type: "String"
                },
                charityNumber: {
                    name: "charityNumber",
                    type: "String",
                    optional: true
                },
                taxRef: {
                    name: "taxRef",
                    type: "String",
                    optional: true
                },
                companyNumber: {
                    name: "companyNumber",
                    type: "String",
                    optional: true
                },
                companyName: {
                    name: "companyName",
                    type: "String",
                    optional: true
                },
                idType: {
                    name: "idType",
                    type: "OrgIdentificationType",
                    default: "UTR_tax_ref"
                },
                identification: {
                    name: "identification",
                    type: "String"
                },
                accountType: {
                    name: "accountType",
                    type: "OrgPlanType",
                    default: "Trial"
                },
                members: {
                    name: "members",
                    type: "Member",
                    array: true,
                    relation: { opposite: "organization" }
                },
                postingPeriods: {
                    name: "postingPeriods",
                    type: "PostingPeriod",
                    array: true,
                    relation: { opposite: "organization" }
                },
                invitations: {
                    name: "invitations",
                    type: "Invitation",
                    array: true,
                    relation: { opposite: "organization" }
                },
                todoLists: {
                    name: "todoLists",
                    type: "TodoList",
                    array: true,
                    relation: { opposite: "organization" }
                },
                funds: {
                    name: "funds",
                    type: "Fund",
                    array: true,
                    relation: { opposite: "organisation", name: "fund" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                slug: { type: "String" }
            }
        },
        Team: {
            name: "Team",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true
                },
                name: {
                    name: "name",
                    type: "String"
                },
                organizationId: {
                    name: "organizationId",
                    type: "String"
                },
                teamMembers: {
                    name: "teamMembers",
                    type: "TeamMember",
                    array: true,
                    relation: { opposite: "team" }
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    default: ExpressionUtils.call("now")
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Member: {
            name: "Member",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true
                },
                organizationId: {
                    name: "organizationId",
                    type: "String",
                    foreignKeyFor: [
                        "organization"
                    ]
                },
                organization: {
                    name: "organization",
                    type: "Organization",
                    relation: { opposite: "members", fields: ["organizationId"], references: ["id"], onDelete: "Cascade" }
                },
                userId: {
                    name: "userId",
                    type: "String",
                    foreignKeyFor: [
                        "user"
                    ]
                },
                user: {
                    name: "user",
                    type: "User",
                    relation: { opposite: "members", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                },
                role: {
                    name: "role",
                    type: "String"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatesAt: {
                    name: "updatesAt",
                    type: "DateTime",
                    updatedAt: true,
                    default: ExpressionUtils.call("now")
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        TeamMember: {
            name: "TeamMember",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true
                },
                teamId: {
                    name: "teamId",
                    type: "String",
                    foreignKeyFor: [
                        "team"
                    ]
                },
                team: {
                    name: "team",
                    type: "Team",
                    relation: { opposite: "teamMembers", fields: ["teamId"], references: ["id"], onDelete: "Cascade" }
                },
                userId: {
                    name: "userId",
                    type: "String",
                    foreignKeyFor: [
                        "user"
                    ]
                },
                user: {
                    name: "user",
                    type: "User",
                    relation: { opposite: "teamMembers", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatesAt: {
                    name: "updatesAt",
                    type: "DateTime",
                    updatedAt: true,
                    default: ExpressionUtils.call("now")
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Invitation: {
            name: "Invitation",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true
                },
                organizationId: {
                    name: "organizationId",
                    type: "String",
                    foreignKeyFor: [
                        "organization"
                    ]
                },
                organization: {
                    name: "organization",
                    type: "Organization",
                    relation: { opposite: "invitations", fields: ["organizationId"], references: ["id"], onDelete: "Cascade" }
                },
                email: {
                    name: "email",
                    type: "String"
                },
                role: {
                    name: "role",
                    type: "String",
                    optional: true
                },
                status: {
                    name: "status",
                    type: "String"
                },
                expiresAt: {
                    name: "expiresAt",
                    type: "DateTime"
                },
                inviterId: {
                    name: "inviterId",
                    type: "String",
                    foreignKeyFor: [
                        "user"
                    ]
                },
                user: {
                    name: "user",
                    type: "User",
                    relation: { opposite: "invitations", fields: ["inviterId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Session: {
            name: "Session",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true
                },
                expiresAt: {
                    name: "expiresAt",
                    type: "DateTime"
                },
                token: {
                    name: "token",
                    type: "String"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime"
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime"
                },
                ipAddress: {
                    name: "ipAddress",
                    type: "String",
                    optional: true
                },
                userAgent: {
                    name: "userAgent",
                    type: "String",
                    optional: true
                },
                userId: {
                    name: "userId",
                    type: "String",
                    foreignKeyFor: [
                        "user"
                    ]
                },
                user: {
                    name: "user",
                    type: "User",
                    relation: { opposite: "sessions", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                },
                activeOrganizationId: {
                    name: "activeOrganizationId",
                    type: "String",
                    optional: true
                },
                impersonatedBy: {
                    name: "impersonatedBy",
                    type: "String",
                    optional: true
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                token: { type: "String" }
            }
        },
        ISOCountry: {
            name: "ISOCountry",
            fields: {
                countryId: {
                    name: "countryId",
                    type: "Int",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                code2: {
                    name: "code2",
                    type: "String",
                    unique: true
                },
                code3: {
                    name: "code3",
                    type: "String",
                    unique: true
                },
                number: {
                    name: "number",
                    type: "Int"
                },
                name: {
                    name: "name",
                    type: "String"
                },
                description: {
                    name: "description",
                    type: "String"
                },
                addresses: {
                    name: "addresses",
                    type: "Address",
                    array: true,
                    relation: { opposite: "country" }
                },
                regions: {
                    name: "regions",
                    type: "AddressRegion",
                    array: true,
                    relation: { opposite: "country" }
                }
            },
            idFields: ["countryId"],
            uniqueFields: {
                countryId: { type: "Int" },
                code2: { type: "String" },
                code3: { type: "String" }
            }
        },
        AddressRegion: {
            name: "AddressRegion",
            fields: {
                regionId: {
                    name: "regionId",
                    type: "Int",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                isoCountryId: {
                    name: "isoCountryId",
                    type: "Int",
                    foreignKeyFor: [
                        "country"
                    ]
                },
                country: {
                    name: "country",
                    type: "ISOCountry",
                    relation: { opposite: "regions", fields: ["isoCountryId"], references: ["countryId"] }
                },
                name: {
                    name: "name",
                    type: "String"
                }
            },
            idFields: ["regionId"],
            uniqueFields: {
                regionId: { type: "Int" }
            }
        },
        Address: {
            name: "Address",
            fields: {
                addressID: {
                    name: "addressID",
                    type: "Int",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                buildingCode: {
                    name: "buildingCode",
                    type: "String",
                    optional: true
                },
                room: {
                    name: "room",
                    type: "String",
                    optional: true
                },
                careOf: {
                    name: "careOf",
                    type: "String",
                    optional: true
                },
                street2: {
                    name: "street2",
                    type: "String",
                    optional: true
                },
                street3: {
                    name: "street3",
                    type: "String",
                    optional: true
                },
                houseNumber: {
                    name: "houseNumber",
                    type: "Int",
                    optional: true
                },
                street: {
                    name: "street",
                    type: "String"
                },
                town: {
                    name: "town",
                    type: "String",
                    optional: true
                },
                county: {
                    name: "county",
                    type: "String",
                    optional: true
                },
                postCode: {
                    name: "postCode",
                    type: "String",
                    optional: true
                },
                isoCountryId: {
                    name: "isoCountryId",
                    type: "Int",
                    foreignKeyFor: [
                        "country"
                    ]
                },
                country: {
                    name: "country",
                    type: "ISOCountry",
                    relation: { opposite: "addresses", fields: ["isoCountryId"], references: ["countryId"] }
                },
                partnerId: {
                    name: "partnerId",
                    type: "String"
                },
                partners: {
                    name: "partners",
                    type: "Partner",
                    array: true,
                    relation: { opposite: "address" }
                },
                companys: {
                    name: "companys",
                    type: "Company",
                    optional: true,
                    relation: { opposite: "regsisteredAddress", name: "registereOfficeAddress" }
                }
            },
            idFields: ["addressID"],
            uniqueFields: {
                addressID: { type: "Int" }
            }
        },
        Apikey: {
            name: "Apikey",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true
                },
                name: {
                    name: "name",
                    type: "String",
                    optional: true
                },
                start: {
                    name: "start",
                    type: "String",
                    optional: true
                },
                prefix: {
                    name: "prefix",
                    type: "String",
                    optional: true
                },
                key: {
                    name: "key",
                    type: "String"
                },
                userId: {
                    name: "userId",
                    type: "String",
                    unique: true,
                    foreignKeyFor: [
                        "user"
                    ]
                },
                user: {
                    name: "user",
                    type: "User",
                    relation: { opposite: "apiKey", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                },
                refillInterval: {
                    name: "refillInterval",
                    type: "Int",
                    optional: true
                },
                refillAmount: {
                    name: "refillAmount",
                    type: "Int",
                    optional: true
                },
                lastRefillAt: {
                    name: "lastRefillAt",
                    type: "DateTime",
                    optional: true
                },
                enabled: {
                    name: "enabled",
                    type: "Boolean",
                    optional: true,
                    default: true
                },
                rateLimitEnabled: {
                    name: "rateLimitEnabled",
                    type: "Boolean",
                    optional: true,
                    default: true
                },
                rateLimitTimeWindow: {
                    name: "rateLimitTimeWindow",
                    type: "Int",
                    optional: true
                },
                rateLimitMax: {
                    name: "rateLimitMax",
                    type: "Int",
                    optional: true
                },
                requestCount: {
                    name: "requestCount",
                    type: "Int",
                    optional: true
                },
                remaining: {
                    name: "remaining",
                    type: "Int",
                    optional: true
                },
                lastRequest: {
                    name: "lastRequest",
                    type: "DateTime",
                    optional: true
                },
                expiresAt: {
                    name: "expiresAt",
                    type: "DateTime",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime"
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime"
                },
                permissions: {
                    name: "permissions",
                    type: "String",
                    optional: true
                },
                metadata: {
                    name: "metadata",
                    type: "String",
                    optional: true
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                userId: { type: "String" }
            }
        },
        GlAccount: {
            name: "GlAccount",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    default: ExpressionUtils.call("uuid")
                },
                name: {
                    name: "name",
                    type: "String"
                },
                balanceSheet: {
                    name: "balanceSheet",
                    type: "Boolean"
                },
                reportCat: {
                    name: "reportCat",
                    type: "String"
                },
                createdById: {
                    name: "createdById",
                    type: "String",
                    foreignKeyFor: [
                        "createdBy"
                    ]
                },
                createdBy: {
                    name: "createdBy",
                    type: "User",
                    relation: { opposite: "glaccounts", fields: ["createdById"], references: ["id"] }
                },
                ArApRecAccount: {
                    name: "ArApRecAccount",
                    type: "ArAPPartner",
                    array: true,
                    relation: { opposite: "reconAccount" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Partner: {
            name: "Partner",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    default: ExpressionUtils.call("uuid")
                },
                name: {
                    name: "name",
                    type: "String"
                },
                personType: {
                    name: "personType",
                    type: "PersonType"
                },
                familyName: {
                    name: "familyName",
                    type: "String",
                    optional: true
                },
                addressId: {
                    name: "addressId",
                    type: "Int",
                    foreignKeyFor: [
                        "address"
                    ]
                },
                searchTerm: {
                    name: "searchTerm",
                    type: "String"
                },
                stripeId: {
                    name: "stripeId",
                    type: "String"
                },
                address: {
                    name: "address",
                    type: "Address",
                    relation: { opposite: "partners", fields: ["addressId"], references: ["addressID"] }
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    default: ExpressionUtils.call("now")
                },
                createdById: {
                    name: "createdById",
                    type: "String",
                    foreignKeyFor: [
                        "createdBy"
                    ]
                },
                createdBy: {
                    name: "createdBy",
                    type: "User",
                    relation: { opposite: "partners", fields: ["createdById"], references: ["id"] }
                },
                type: {
                    name: "type",
                    type: "String",
                    isDiscriminator: true
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            },
            isDelegate: true,
            subModels: ["ArAPPartner"]
        },
        ArAPPartner: {
            name: "ArAPPartner",
            baseModel: "Partner",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    default: ExpressionUtils.call("uuid")
                },
                name: {
                    name: "name",
                    type: "String",
                    originModel: "Partner"
                },
                personType: {
                    name: "personType",
                    type: "PersonType",
                    originModel: "Partner"
                },
                familyName: {
                    name: "familyName",
                    type: "String",
                    optional: true,
                    originModel: "Partner"
                },
                addressId: {
                    name: "addressId",
                    type: "Int",
                    originModel: "Partner",
                    foreignKeyFor: [
                        "address"
                    ]
                },
                searchTerm: {
                    name: "searchTerm",
                    type: "String",
                    originModel: "Partner"
                },
                stripeId: {
                    name: "stripeId",
                    type: "String",
                    originModel: "Partner"
                },
                address: {
                    name: "address",
                    type: "Address",
                    originModel: "Partner",
                    relation: { opposite: "partners", fields: ["addressId"], references: ["addressID"] }
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    originModel: "Partner",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    originModel: "Partner",
                    default: ExpressionUtils.call("now")
                },
                createdById: {
                    name: "createdById",
                    type: "String",
                    originModel: "Partner",
                    foreignKeyFor: [
                        "createdBy"
                    ]
                },
                createdBy: {
                    name: "createdBy",
                    type: "User",
                    originModel: "Partner",
                    relation: { opposite: "partners", fields: ["createdById"], references: ["id"] }
                },
                type: {
                    name: "type",
                    type: "String",
                    originModel: "Partner",
                    isDiscriminator: true
                },
                reconAccountId: {
                    name: "reconAccountId",
                    type: "String",
                    foreignKeyFor: [
                        "reconAccount"
                    ]
                },
                reconAccount: {
                    name: "reconAccount",
                    type: "GlAccount",
                    relation: { opposite: "ArApRecAccount", fields: ["reconAccountId"], references: ["id"] }
                },
                companyId: {
                    name: "companyId",
                    type: "String"
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        FiscalPeriodRule: {
            name: "FiscalPeriodRule",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                name: {
                    name: "name",
                    type: "String"
                },
                monthNum: {
                    name: "monthNum",
                    type: "Int"
                },
                day: {
                    name: "day",
                    type: "Int"
                },
                fiscPeriod: {
                    name: "fiscPeriod",
                    type: "Int"
                },
                yearShift: {
                    name: "yearShift",
                    type: "Boolean"
                },
                calendarBased: {
                    name: "calendarBased",
                    type: "Boolean"
                },
                companies: {
                    name: "companies",
                    type: "Company",
                    array: true,
                    relation: { opposite: "fiscPeriodRule", name: "fiscPeriodRule" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" }
            }
        },
        Parameter: {
            name: "Parameter",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                name: {
                    name: "name",
                    type: "String"
                },
                value: {
                    name: "value",
                    type: "String"
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" }
            }
        },
        Company: {
            name: "Company",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                companyCode: {
                    name: "companyCode",
                    type: "String"
                },
                companyName: {
                    name: "companyName",
                    type: "String"
                },
                registeredOfficeAddressId: {
                    name: "registeredOfficeAddressId",
                    type: "Int",
                    unique: true,
                    foreignKeyFor: [
                        "regsisteredAddress"
                    ]
                },
                regsisteredAddress: {
                    name: "regsisteredAddress",
                    type: "Address",
                    relation: { opposite: "companys", name: "registereOfficeAddress", fields: ["registeredOfficeAddressId"], references: ["addressID"] }
                },
                vatNumber: {
                    name: "vatNumber",
                    type: "String",
                    optional: true
                },
                fiscalPeriodRuleId: {
                    name: "fiscalPeriodRuleId",
                    type: "Int",
                    foreignKeyFor: [
                        "fiscPeriodRule"
                    ]
                },
                fiscPeriodRule: {
                    name: "fiscPeriodRule",
                    type: "FiscalPeriodRule",
                    relation: { opposite: "companies", name: "fiscPeriodRule", fields: ["fiscalPeriodRuleId"], references: ["id"] }
                },
                postPeriod: {
                    name: "postPeriod",
                    type: "CompanyPostingPeriod",
                    array: true,
                    relation: { opposite: "company" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" },
                registeredOfficeAddressId: { type: "Int" }
            }
        },
        CompanyPostingPeriod: {
            name: "CompanyPostingPeriod",
            fields: {
                companyId: {
                    name: "companyId",
                    type: "Int",
                    id: true,
                    foreignKeyFor: [
                        "company"
                    ]
                },
                postingPeriodId: {
                    name: "postingPeriodId",
                    type: "Int",
                    id: true,
                    foreignKeyFor: [
                        "postPeriod"
                    ]
                },
                company: {
                    name: "company",
                    type: "Company",
                    relation: { opposite: "postPeriod", fields: ["companyId"], references: ["id"] }
                },
                postPeriod: {
                    name: "postPeriod",
                    type: "PostingPeriod",
                    relation: { opposite: "postPeriod", fields: ["postingPeriodId"], references: ["id"] }
                }
            },
            idFields: ["companyId", "postingPeriodId"],
            uniqueFields: {
                companyId_postingPeriodId: { companyId: { type: "Int" }, postingPeriodId: { type: "Int" } }
            }
        },
        Fund: {
            name: "Fund",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    default: ExpressionUtils.call("uuid")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    default: ExpressionUtils.call("now")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                fundName: {
                    name: "fundName",
                    type: "String"
                },
                donarName: {
                    name: "donarName",
                    type: "String",
                    optional: true
                },
                objective: {
                    name: "objective",
                    type: "String",
                    optional: true
                },
                managedById: {
                    name: "managedById",
                    type: "String",
                    foreignKeyFor: [
                        "createdBy"
                    ]
                },
                organisationId: {
                    name: "organisationId",
                    type: "String",
                    foreignKeyFor: [
                        "organisation"
                    ]
                },
                organisation: {
                    name: "organisation",
                    type: "Organization",
                    relation: { opposite: "funds", name: "fund", fields: ["organisationId"], references: ["id"], onDelete: "Cascade" }
                },
                createdBy: {
                    name: "createdBy",
                    type: "User",
                    relation: { opposite: "funds", fields: ["managedById"], references: ["id"] }
                },
                fundType: {
                    name: "fundType",
                    type: "String",
                    default: "General"
                },
                reviewDate: {
                    name: "reviewDate",
                    type: "DateTime",
                    optional: true
                },
                type: {
                    name: "type",
                    type: "String",
                    isDiscriminator: true
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            },
            isDelegate: true,
            subModels: ["GeneralFund", "RestrictedFund"]
        },
        GeneralFund: {
            name: "GeneralFund",
            baseModel: "Fund",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    default: ExpressionUtils.call("uuid")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    originModel: "Fund",
                    default: ExpressionUtils.call("now")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    originModel: "Fund",
                    default: ExpressionUtils.call("now")
                },
                fundName: {
                    name: "fundName",
                    type: "String",
                    originModel: "Fund"
                },
                donarName: {
                    name: "donarName",
                    type: "String",
                    optional: true,
                    originModel: "Fund"
                },
                objective: {
                    name: "objective",
                    type: "String",
                    optional: true,
                    originModel: "Fund"
                },
                managedById: {
                    name: "managedById",
                    type: "String",
                    originModel: "Fund",
                    foreignKeyFor: [
                        "createdBy"
                    ]
                },
                organisationId: {
                    name: "organisationId",
                    type: "String",
                    originModel: "Fund",
                    foreignKeyFor: [
                        "organisation"
                    ]
                },
                organisation: {
                    name: "organisation",
                    type: "Organization",
                    originModel: "Fund",
                    relation: { opposite: "funds", name: "fund", fields: ["organisationId"], references: ["id"], onDelete: "Cascade" }
                },
                createdBy: {
                    name: "createdBy",
                    type: "User",
                    originModel: "Fund",
                    relation: { opposite: "funds", fields: ["managedById"], references: ["id"] }
                },
                fundType: {
                    name: "fundType",
                    type: "String",
                    originModel: "Fund",
                    default: "General"
                },
                reviewDate: {
                    name: "reviewDate",
                    type: "DateTime",
                    optional: true,
                    originModel: "Fund"
                },
                type: {
                    name: "type",
                    type: "String",
                    originModel: "Fund",
                    isDiscriminator: true
                },
                balance: {
                    name: "balance",
                    type: "Decimal",
                    optional: true
                },
                balances: {
                    name: "balances",
                    type: "FundBalance",
                    array: true,
                    relation: { opposite: "generalFund", name: "genFundBal" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        RestrictedFund: {
            name: "RestrictedFund",
            baseModel: "Fund",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    default: ExpressionUtils.call("uuid")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    originModel: "Fund",
                    default: ExpressionUtils.call("now")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    originModel: "Fund",
                    default: ExpressionUtils.call("now")
                },
                fundName: {
                    name: "fundName",
                    type: "String",
                    originModel: "Fund"
                },
                donarName: {
                    name: "donarName",
                    type: "String",
                    optional: true,
                    originModel: "Fund"
                },
                objective: {
                    name: "objective",
                    type: "String",
                    optional: true,
                    originModel: "Fund"
                },
                managedById: {
                    name: "managedById",
                    type: "String",
                    originModel: "Fund",
                    foreignKeyFor: [
                        "createdBy"
                    ]
                },
                organisationId: {
                    name: "organisationId",
                    type: "String",
                    originModel: "Fund",
                    foreignKeyFor: [
                        "organisation"
                    ]
                },
                organisation: {
                    name: "organisation",
                    type: "Organization",
                    originModel: "Fund",
                    relation: { opposite: "funds", name: "fund", fields: ["organisationId"], references: ["id"], onDelete: "Cascade" }
                },
                createdBy: {
                    name: "createdBy",
                    type: "User",
                    originModel: "Fund",
                    relation: { opposite: "funds", fields: ["managedById"], references: ["id"] }
                },
                fundType: {
                    name: "fundType",
                    type: "String",
                    originModel: "Fund",
                    default: "General"
                },
                reviewDate: {
                    name: "reviewDate",
                    type: "DateTime",
                    optional: true,
                    originModel: "Fund"
                },
                type: {
                    name: "type",
                    type: "String",
                    originModel: "Fund",
                    isDiscriminator: true
                },
                projectEndDate: {
                    name: "projectEndDate",
                    type: "DateTime"
                },
                restrictedType: {
                    name: "restrictedType",
                    type: "String",
                    isDiscriminator: true
                },
                nextDonarReviewDate: {
                    name: "nextDonarReviewDate",
                    type: "DateTime",
                    optional: true
                },
                returnSurplus: {
                    name: "returnSurplus",
                    type: "Boolean",
                    optional: true
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            },
            isDelegate: true,
            subModels: ["DesignatedFund", "IncomeFund", "EndownmentPermanent", "EndownmentExpendable"]
        },
        DesignatedFund: {
            name: "DesignatedFund",
            baseModel: "RestrictedFund",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    default: ExpressionUtils.call("uuid")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    originModel: "Fund",
                    default: ExpressionUtils.call("now")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    originModel: "Fund",
                    default: ExpressionUtils.call("now")
                },
                fundName: {
                    name: "fundName",
                    type: "String",
                    originModel: "Fund"
                },
                donarName: {
                    name: "donarName",
                    type: "String",
                    optional: true,
                    originModel: "Fund"
                },
                objective: {
                    name: "objective",
                    type: "String",
                    optional: true,
                    originModel: "Fund"
                },
                managedById: {
                    name: "managedById",
                    type: "String",
                    originModel: "Fund",
                    foreignKeyFor: [
                        "createdBy"
                    ]
                },
                organisationId: {
                    name: "organisationId",
                    type: "String",
                    originModel: "Fund",
                    foreignKeyFor: [
                        "organisation"
                    ]
                },
                organisation: {
                    name: "organisation",
                    type: "Organization",
                    originModel: "Fund",
                    relation: { opposite: "funds", name: "fund", fields: ["organisationId"], references: ["id"], onDelete: "Cascade" }
                },
                createdBy: {
                    name: "createdBy",
                    type: "User",
                    originModel: "Fund",
                    relation: { opposite: "funds", fields: ["managedById"], references: ["id"] }
                },
                fundType: {
                    name: "fundType",
                    type: "String",
                    originModel: "Fund",
                    default: "General"
                },
                reviewDate: {
                    name: "reviewDate",
                    type: "DateTime",
                    optional: true,
                    originModel: "Fund"
                },
                type: {
                    name: "type",
                    type: "String",
                    originModel: "Fund",
                    isDiscriminator: true
                },
                projectEndDate: {
                    name: "projectEndDate",
                    type: "DateTime",
                    originModel: "RestrictedFund"
                },
                restrictedType: {
                    name: "restrictedType",
                    type: "String",
                    originModel: "RestrictedFund",
                    isDiscriminator: true
                },
                nextDonarReviewDate: {
                    name: "nextDonarReviewDate",
                    type: "DateTime",
                    optional: true,
                    originModel: "RestrictedFund"
                },
                returnSurplus: {
                    name: "returnSurplus",
                    type: "Boolean",
                    optional: true,
                    originModel: "RestrictedFund"
                },
                designatedBal: {
                    name: "designatedBal",
                    type: "Decimal",
                    optional: true
                },
                currentBal: {
                    name: "currentBal",
                    type: "Decimal",
                    optional: true
                },
                designatedDate: {
                    name: "designatedDate",
                    type: "DateTime"
                },
                releasedDate: {
                    name: "releasedDate",
                    type: "DateTime",
                    optional: true
                },
                designatedById: {
                    name: "designatedById",
                    type: "String",
                    foreignKeyFor: [
                        "designatedBy"
                    ]
                },
                designateMeeting: {
                    name: "designateMeeting",
                    type: "String"
                },
                undesignateMeeting: {
                    name: "undesignateMeeting",
                    type: "String",
                    optional: true
                },
                designationReleasedById: {
                    name: "designationReleasedById",
                    type: "String",
                    optional: true,
                    foreignKeyFor: [
                        "designationReleasedBy"
                    ]
                },
                designationCreatedById: {
                    name: "designationCreatedById",
                    type: "String",
                    foreignKeyFor: [
                        "designationCreatedBy"
                    ]
                },
                designatedBy: {
                    name: "designatedBy",
                    type: "User",
                    optional: true,
                    relation: { opposite: "designatedFund", name: "designatedBy", fields: ["designatedById"], references: ["id"] }
                },
                designationCreatedBy: {
                    name: "designationCreatedBy",
                    type: "User",
                    relation: { opposite: "createdDesignatedFund", name: "designationCreate", fields: ["designationCreatedById"], references: ["id"] }
                },
                designationReleasedBy: {
                    name: "designationReleasedBy",
                    type: "User",
                    optional: true,
                    relation: { opposite: "releasedDesignatedFund", name: "designationRelease", fields: ["designationReleasedById"], references: ["id"] }
                },
                balances: {
                    name: "balances",
                    type: "FundBalance",
                    array: true,
                    relation: { opposite: "designatedfund", name: "designatedBal" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        IncomeFund: {
            name: "IncomeFund",
            baseModel: "RestrictedFund",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    default: ExpressionUtils.call("uuid")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    originModel: "Fund",
                    default: ExpressionUtils.call("now")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    originModel: "Fund",
                    default: ExpressionUtils.call("now")
                },
                fundName: {
                    name: "fundName",
                    type: "String",
                    originModel: "Fund"
                },
                donarName: {
                    name: "donarName",
                    type: "String",
                    optional: true,
                    originModel: "Fund"
                },
                objective: {
                    name: "objective",
                    type: "String",
                    optional: true,
                    originModel: "Fund"
                },
                managedById: {
                    name: "managedById",
                    type: "String",
                    originModel: "Fund",
                    foreignKeyFor: [
                        "createdBy"
                    ]
                },
                organisationId: {
                    name: "organisationId",
                    type: "String",
                    originModel: "Fund",
                    foreignKeyFor: [
                        "organisation"
                    ]
                },
                organisation: {
                    name: "organisation",
                    type: "Organization",
                    originModel: "Fund",
                    relation: { opposite: "funds", name: "fund", fields: ["organisationId"], references: ["id"], onDelete: "Cascade" }
                },
                createdBy: {
                    name: "createdBy",
                    type: "User",
                    originModel: "Fund",
                    relation: { opposite: "funds", fields: ["managedById"], references: ["id"] }
                },
                fundType: {
                    name: "fundType",
                    type: "String",
                    originModel: "Fund",
                    default: "General"
                },
                reviewDate: {
                    name: "reviewDate",
                    type: "DateTime",
                    optional: true,
                    originModel: "Fund"
                },
                type: {
                    name: "type",
                    type: "String",
                    originModel: "Fund",
                    isDiscriminator: true
                },
                projectEndDate: {
                    name: "projectEndDate",
                    type: "DateTime",
                    originModel: "RestrictedFund"
                },
                restrictedType: {
                    name: "restrictedType",
                    type: "String",
                    originModel: "RestrictedFund",
                    isDiscriminator: true
                },
                nextDonarReviewDate: {
                    name: "nextDonarReviewDate",
                    type: "DateTime",
                    optional: true,
                    originModel: "RestrictedFund"
                },
                returnSurplus: {
                    name: "returnSurplus",
                    type: "Boolean",
                    optional: true,
                    originModel: "RestrictedFund"
                },
                balance: {
                    name: "balance",
                    type: "Decimal",
                    optional: true
                },
                balances: {
                    name: "balances",
                    type: "FundBalance",
                    array: true,
                    relation: { opposite: "incomeFund", name: "incomeFundBal" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        EndownmentPermanent: {
            name: "EndownmentPermanent",
            baseModel: "RestrictedFund",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    default: ExpressionUtils.call("uuid")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    originModel: "Fund",
                    default: ExpressionUtils.call("now")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    originModel: "Fund",
                    default: ExpressionUtils.call("now")
                },
                fundName: {
                    name: "fundName",
                    type: "String",
                    originModel: "Fund"
                },
                donarName: {
                    name: "donarName",
                    type: "String",
                    optional: true,
                    originModel: "Fund"
                },
                objective: {
                    name: "objective",
                    type: "String",
                    optional: true,
                    originModel: "Fund"
                },
                managedById: {
                    name: "managedById",
                    type: "String",
                    originModel: "Fund",
                    foreignKeyFor: [
                        "createdBy"
                    ]
                },
                organisationId: {
                    name: "organisationId",
                    type: "String",
                    originModel: "Fund",
                    foreignKeyFor: [
                        "organisation"
                    ]
                },
                organisation: {
                    name: "organisation",
                    type: "Organization",
                    originModel: "Fund",
                    relation: { opposite: "funds", name: "fund", fields: ["organisationId"], references: ["id"], onDelete: "Cascade" }
                },
                createdBy: {
                    name: "createdBy",
                    type: "User",
                    originModel: "Fund",
                    relation: { opposite: "funds", fields: ["managedById"], references: ["id"] }
                },
                fundType: {
                    name: "fundType",
                    type: "String",
                    originModel: "Fund",
                    default: "General"
                },
                reviewDate: {
                    name: "reviewDate",
                    type: "DateTime",
                    optional: true,
                    originModel: "Fund"
                },
                type: {
                    name: "type",
                    type: "String",
                    originModel: "Fund",
                    isDiscriminator: true
                },
                projectEndDate: {
                    name: "projectEndDate",
                    type: "DateTime",
                    originModel: "RestrictedFund"
                },
                restrictedType: {
                    name: "restrictedType",
                    type: "String",
                    originModel: "RestrictedFund",
                    isDiscriminator: true
                },
                nextDonarReviewDate: {
                    name: "nextDonarReviewDate",
                    type: "DateTime",
                    optional: true,
                    originModel: "RestrictedFund"
                },
                returnSurplus: {
                    name: "returnSurplus",
                    type: "Boolean",
                    optional: true,
                    originModel: "RestrictedFund"
                },
                initalCapitalAmount: {
                    name: "initalCapitalAmount",
                    type: "Decimal",
                    optional: true
                },
                incomeBalance: {
                    name: "incomeBalance",
                    type: "Decimal",
                    optional: true
                },
                capitalBalance: {
                    name: "capitalBalance",
                    type: "Decimal",
                    optional: true
                },
                permanentIncomeBalances: {
                    name: "permanentIncomeBalances",
                    type: "FundBalance",
                    array: true,
                    relation: { opposite: "permanentIncomefund", name: "permanentIncomeFundBal" }
                },
                permanentCapitalBalances: {
                    name: "permanentCapitalBalances",
                    type: "FundBalance",
                    array: true,
                    relation: { opposite: "permanentCapitalfund", name: "permanentCapitalFundBal" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        EndownmentExpendable: {
            name: "EndownmentExpendable",
            baseModel: "RestrictedFund",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    default: ExpressionUtils.call("uuid")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    originModel: "Fund",
                    default: ExpressionUtils.call("now")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    originModel: "Fund",
                    default: ExpressionUtils.call("now")
                },
                fundName: {
                    name: "fundName",
                    type: "String",
                    originModel: "Fund"
                },
                donarName: {
                    name: "donarName",
                    type: "String",
                    optional: true,
                    originModel: "Fund"
                },
                objective: {
                    name: "objective",
                    type: "String",
                    optional: true,
                    originModel: "Fund"
                },
                managedById: {
                    name: "managedById",
                    type: "String",
                    originModel: "Fund",
                    foreignKeyFor: [
                        "createdBy"
                    ]
                },
                organisationId: {
                    name: "organisationId",
                    type: "String",
                    originModel: "Fund",
                    foreignKeyFor: [
                        "organisation"
                    ]
                },
                organisation: {
                    name: "organisation",
                    type: "Organization",
                    originModel: "Fund",
                    relation: { opposite: "funds", name: "fund", fields: ["organisationId"], references: ["id"], onDelete: "Cascade" }
                },
                createdBy: {
                    name: "createdBy",
                    type: "User",
                    originModel: "Fund",
                    relation: { opposite: "funds", fields: ["managedById"], references: ["id"] }
                },
                fundType: {
                    name: "fundType",
                    type: "String",
                    originModel: "Fund",
                    default: "General"
                },
                reviewDate: {
                    name: "reviewDate",
                    type: "DateTime",
                    optional: true,
                    originModel: "Fund"
                },
                type: {
                    name: "type",
                    type: "String",
                    originModel: "Fund",
                    isDiscriminator: true
                },
                projectEndDate: {
                    name: "projectEndDate",
                    type: "DateTime",
                    originModel: "RestrictedFund"
                },
                restrictedType: {
                    name: "restrictedType",
                    type: "String",
                    originModel: "RestrictedFund",
                    isDiscriminator: true
                },
                nextDonarReviewDate: {
                    name: "nextDonarReviewDate",
                    type: "DateTime",
                    optional: true,
                    originModel: "RestrictedFund"
                },
                returnSurplus: {
                    name: "returnSurplus",
                    type: "Boolean",
                    optional: true,
                    originModel: "RestrictedFund"
                },
                initalCapitalAmount: {
                    name: "initalCapitalAmount",
                    type: "Decimal",
                    optional: true
                },
                incomeAmount: {
                    name: "incomeAmount",
                    type: "Decimal",
                    optional: true
                },
                incomeBalance: {
                    name: "incomeBalance",
                    type: "Decimal",
                    optional: true
                },
                capitalBalance: {
                    name: "capitalBalance",
                    type: "Decimal",
                    optional: true
                },
                expendableIncomeBalances: {
                    name: "expendableIncomeBalances",
                    type: "FundBalance",
                    array: true,
                    relation: { opposite: "expendableIncomefund", name: "expendableIncomeFundBal" }
                },
                expendableCapitalBalances: {
                    name: "expendableCapitalBalances",
                    type: "FundBalance",
                    array: true,
                    relation: { opposite: "expendableCapitalfund", name: "expendableCapitalFundBal" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        FundBalance: {
            name: "FundBalance",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    default: ExpressionUtils.call("uuid")
                },
                fiscalPeriod: {
                    name: "fiscalPeriod",
                    type: "Int"
                },
                fiscalYear: {
                    name: "fiscalYear",
                    type: "Int"
                },
                balance: {
                    name: "balance",
                    type: "Decimal"
                },
                generalFundId: {
                    name: "generalFundId",
                    type: "String",
                    optional: true,
                    foreignKeyFor: [
                        "generalFund"
                    ]
                },
                generalFund: {
                    name: "generalFund",
                    type: "GeneralFund",
                    optional: true,
                    relation: { opposite: "balances", name: "genFundBal", fields: ["generalFundId"], references: ["id"] }
                },
                incomeFundId: {
                    name: "incomeFundId",
                    type: "String",
                    optional: true,
                    foreignKeyFor: [
                        "incomeFund"
                    ]
                },
                incomeFund: {
                    name: "incomeFund",
                    type: "IncomeFund",
                    optional: true,
                    relation: { opposite: "balances", name: "incomeFundBal", fields: ["incomeFundId"], references: ["id"] }
                },
                designiatedFundId: {
                    name: "designiatedFundId",
                    type: "String",
                    optional: true,
                    foreignKeyFor: [
                        "designatedfund"
                    ]
                },
                designatedfund: {
                    name: "designatedfund",
                    type: "DesignatedFund",
                    optional: true,
                    relation: { opposite: "balances", name: "designatedBal", fields: ["designiatedFundId"], references: ["id"] }
                },
                expendableIncomeFundId: {
                    name: "expendableIncomeFundId",
                    type: "String",
                    optional: true,
                    foreignKeyFor: [
                        "expendableIncomefund"
                    ]
                },
                expendableIncomefund: {
                    name: "expendableIncomefund",
                    type: "EndownmentExpendable",
                    optional: true,
                    relation: { opposite: "expendableIncomeBalances", name: "expendableIncomeFundBal", fields: ["expendableIncomeFundId"], references: ["id"] }
                },
                expendableCapitalFundId: {
                    name: "expendableCapitalFundId",
                    type: "String",
                    optional: true,
                    foreignKeyFor: [
                        "expendableCapitalfund"
                    ]
                },
                expendableCapitalfund: {
                    name: "expendableCapitalfund",
                    type: "EndownmentExpendable",
                    optional: true,
                    relation: { opposite: "expendableCapitalBalances", name: "expendableCapitalFundBal", fields: ["expendableCapitalFundId"], references: ["id"] }
                },
                permanentIncomeFundId: {
                    name: "permanentIncomeFundId",
                    type: "String",
                    optional: true,
                    foreignKeyFor: [
                        "permanentIncomefund"
                    ]
                },
                permanentIncomefund: {
                    name: "permanentIncomefund",
                    type: "EndownmentPermanent",
                    optional: true,
                    relation: { opposite: "permanentIncomeBalances", name: "permanentIncomeFundBal", fields: ["permanentIncomeFundId"], references: ["id"] }
                },
                permanentCapitalFundId: {
                    name: "permanentCapitalFundId",
                    type: "String",
                    optional: true,
                    foreignKeyFor: [
                        "permanentCapitalfund"
                    ]
                },
                permanentCapitalfund: {
                    name: "permanentCapitalfund",
                    type: "EndownmentPermanent",
                    optional: true,
                    relation: { opposite: "permanentCapitalBalances", name: "permanentCapitalFundBal", fields: ["permanentCapitalFundId"], references: ["id"] }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        JournalDoc: {
            name: "JournalDoc",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    default: ExpressionUtils.call("uuid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true
                },
                ref: {
                    name: "ref",
                    type: "String"
                },
                year: {
                    name: "year",
                    type: "Int"
                },
                fiscalPeriod: {
                    name: "fiscalPeriod",
                    type: "Int"
                },
                headerText: {
                    name: "headerText",
                    type: "String"
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        }
    } as const;
    typeDefs = {
        Auth: {
            name: "Auth",
            fields: {
                userId: {
                    name: "userId",
                    type: "String"
                },
                organizationId: {
                    name: "organizationId",
                    type: "String",
                    optional: true
                },
                organizationRole: {
                    name: "organizationRole",
                    type: "String",
                    optional: true
                },
                role: {
                    name: "role",
                    type: "String"
                }
            },
            attributes: [
                { name: "@@auth" }
            ]
        }
    } as const;
    enums = {
        Role: {
            name: "Role",
            values: {
                MANAGER: "MANAGER",
                RECEIVABLE_POSTER: "RECEIVABLE_POSTER",
                PAYABLE_POSTER: "PAYABLE_POSTER",
                GL_POSTER: "GL_POSTER",
                RECEIVABLE_DISPLAY: "RECEIVABLE_DISPLAY",
                CLERK: "CLERK",
                user: "user",
                member: "member",
                admin: "admin",
                ORG_ADMIN: "ORG_ADMIN"
            }
        },
        OrgLegalForm: {
            name: "OrgLegalForm",
            values: {
                SoleTrader: "SoleTrader",
                Company: "Company",
                Partnership: "Partnership"
            }
        },
        OrgIdentificationType: {
            name: "OrgIdentificationType",
            values: {
                UTR_tax_ref: "UTR_tax_ref",
                Company_Number: "Company_Number",
                Charity_number: "Charity_number"
            }
        },
        OrgPlanType: {
            name: "OrgPlanType",
            values: {
                Trial: "Trial",
                Free: "Free",
                Standard: "Standard",
                Premium: "Premium"
            }
        },
        PersonType: {
            name: "PersonType",
            values: {
                Person: "Person",
                Organisation: "Organisation"
            }
        },
        FundType: {
            name: "FundType",
            values: {
                General: "General",
                Designated: "Designated",
                Income: "Income",
                Expendable: "Expendable",
                Permanent: "Permanent"
            }
        }
    } as const;
    authType = "Auth" as const;
    plugins = {};
}
export const schema = new SchemaType();
