//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, ExpressionUtils } from "@zenstackhq/orm/schema";
export class SchemaType implements SchemaDef {
    provider = {
        type: "postgresql",
        defaultSchema: "charitatis"
    } as const;
    models = {
        TodoList: {
            name: "TodoList",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    default: ExpressionUtils.call("cuid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true
                },
                name: {
                    name: "name",
                    type: "String"
                },
                owner: {
                    name: "owner",
                    type: "User",
                    relation: { opposite: "todoLists", fields: ["ownerId"], references: ["id"], onDelete: "Cascade", hasDefault: true }
                },
                ownerId: {
                    name: "ownerId",
                    type: "String",
                    default: ExpressionUtils.member(ExpressionUtils.call("auth"), ["userId"]),
                    foreignKeyFor: [
                        "owner"
                    ]
                },
                organization: {
                    name: "organization",
                    type: "Organization",
                    optional: true,
                    relation: { opposite: "todoLists", fields: ["organizationId"], references: ["id"], onDelete: "Cascade", hasDefault: true }
                },
                organizationId: {
                    name: "organizationId",
                    type: "String",
                    optional: true,
                    default: ExpressionUtils.member(ExpressionUtils.call("auth"), ["organizationId"]),
                    foreignKeyFor: [
                        "organization"
                    ]
                },
                todos: {
                    name: "todos",
                    type: "Todo",
                    array: true,
                    relation: { opposite: "list" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Todo: {
            name: "Todo",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    default: ExpressionUtils.call("cuid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true
                },
                title: {
                    name: "title",
                    type: "String"
                },
                done: {
                    name: "done",
                    type: "Boolean",
                    default: false
                },
                listId: {
                    name: "listId",
                    type: "String",
                    foreignKeyFor: [
                        "list"
                    ]
                },
                list: {
                    name: "list",
                    type: "TodoList",
                    relation: { opposite: "todos", fields: ["listId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        User: {
            name: "User",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true
                },
                name: {
                    name: "name",
                    type: "String"
                },
                email: {
                    name: "email",
                    type: "String",
                    unique: true
                },
                emailVerified: {
                    name: "emailVerified",
                    type: "Boolean",
                    default: false
                },
                image: {
                    name: "image",
                    type: "String",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    default: ExpressionUtils.call("now")
                },
                role: {
                    name: "role",
                    type: "String",
                    optional: true
                },
                banned: {
                    name: "banned",
                    type: "Boolean",
                    optional: true
                },
                banReason: {
                    name: "banReason",
                    type: "String",
                    optional: true
                },
                banExpires: {
                    name: "banExpires",
                    type: "DateTime",
                    optional: true
                },
                sessions: {
                    name: "sessions",
                    type: "Session",
                    array: true,
                    relation: { opposite: "user" }
                },
                accounts: {
                    name: "accounts",
                    type: "Account",
                    array: true,
                    relation: { opposite: "user" }
                },
                members: {
                    name: "members",
                    type: "Member",
                    array: true,
                    relation: { opposite: "user" }
                },
                invitations: {
                    name: "invitations",
                    type: "Invitation",
                    array: true,
                    relation: { opposite: "user" }
                },
                todoLists: {
                    name: "todoLists",
                    type: "TodoList",
                    array: true,
                    relation: { opposite: "owner" }
                },
                apiKey: {
                    name: "apiKey",
                    type: "Apikey",
                    optional: true,
                    relation: { opposite: "user" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                email: { type: "String" }
            }
        },
        Account: {
            name: "Account",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true
                },
                accountId: {
                    name: "accountId",
                    type: "String"
                },
                providerId: {
                    name: "providerId",
                    type: "String"
                },
                userId: {
                    name: "userId",
                    type: "String",
                    foreignKeyFor: [
                        "user"
                    ]
                },
                user: {
                    name: "user",
                    type: "User",
                    relation: { opposite: "accounts", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                },
                accessToken: {
                    name: "accessToken",
                    type: "String",
                    optional: true
                },
                refreshToken: {
                    name: "refreshToken",
                    type: "String",
                    optional: true
                },
                idToken: {
                    name: "idToken",
                    type: "String",
                    optional: true
                },
                accessTokenExpiresAt: {
                    name: "accessTokenExpiresAt",
                    type: "DateTime",
                    optional: true
                },
                refreshTokenExpiresAt: {
                    name: "refreshTokenExpiresAt",
                    type: "DateTime",
                    optional: true
                },
                scope: {
                    name: "scope",
                    type: "String",
                    optional: true
                },
                password: {
                    name: "password",
                    type: "String",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Verification: {
            name: "Verification",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true
                },
                identifier: {
                    name: "identifier",
                    type: "String"
                },
                value: {
                    name: "value",
                    type: "String"
                },
                expiresAt: {
                    name: "expiresAt",
                    type: "DateTime"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    optional: true,
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    optional: true,
                    updatedAt: true,
                    default: ExpressionUtils.call("now")
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Organization: {
            name: "Organization",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true
                },
                name: {
                    name: "name",
                    type: "String"
                },
                slug: {
                    name: "slug",
                    type: "String",
                    unique: true,
                    optional: true
                },
                logo: {
                    name: "logo",
                    type: "String",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime"
                },
                metadata: {
                    name: "metadata",
                    type: "String",
                    optional: true
                },
                members: {
                    name: "members",
                    type: "Member",
                    array: true,
                    relation: { opposite: "organization" }
                },
                invitations: {
                    name: "invitations",
                    type: "Invitation",
                    array: true,
                    relation: { opposite: "organization" }
                },
                todoLists: {
                    name: "todoLists",
                    type: "TodoList",
                    array: true,
                    relation: { opposite: "organization" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                slug: { type: "String" }
            }
        },
        Member: {
            name: "Member",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true
                },
                organizationId: {
                    name: "organizationId",
                    type: "String",
                    foreignKeyFor: [
                        "organization"
                    ]
                },
                organization: {
                    name: "organization",
                    type: "Organization",
                    relation: { opposite: "members", fields: ["organizationId"], references: ["id"], onDelete: "Cascade" }
                },
                userId: {
                    name: "userId",
                    type: "String",
                    foreignKeyFor: [
                        "user"
                    ]
                },
                user: {
                    name: "user",
                    type: "User",
                    relation: { opposite: "members", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                },
                role: {
                    name: "role",
                    type: "String"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime"
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Invitation: {
            name: "Invitation",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true
                },
                organizationId: {
                    name: "organizationId",
                    type: "String",
                    foreignKeyFor: [
                        "organization"
                    ]
                },
                organization: {
                    name: "organization",
                    type: "Organization",
                    relation: { opposite: "invitations", fields: ["organizationId"], references: ["id"], onDelete: "Cascade" }
                },
                email: {
                    name: "email",
                    type: "String"
                },
                role: {
                    name: "role",
                    type: "String",
                    optional: true
                },
                status: {
                    name: "status",
                    type: "String"
                },
                expiresAt: {
                    name: "expiresAt",
                    type: "DateTime"
                },
                inviterId: {
                    name: "inviterId",
                    type: "String",
                    foreignKeyFor: [
                        "user"
                    ]
                },
                user: {
                    name: "user",
                    type: "User",
                    relation: { opposite: "invitations", fields: ["inviterId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Session: {
            name: "Session",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true
                },
                expiresAt: {
                    name: "expiresAt",
                    type: "DateTime"
                },
                token: {
                    name: "token",
                    type: "String"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime"
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime"
                },
                ipAddress: {
                    name: "ipAddress",
                    type: "String",
                    optional: true
                },
                userAgent: {
                    name: "userAgent",
                    type: "String",
                    optional: true
                },
                userId: {
                    name: "userId",
                    type: "String",
                    foreignKeyFor: [
                        "user"
                    ]
                },
                user: {
                    name: "user",
                    type: "User",
                    relation: { opposite: "sessions", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                },
                activeOrganizationId: {
                    name: "activeOrganizationId",
                    type: "String",
                    optional: true
                },
                impersonatedBy: {
                    name: "impersonatedBy",
                    type: "String",
                    optional: true
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                token: { type: "String" }
            }
        },
        ISOCountry: {
            name: "ISOCountry",
            fields: {
                countryId: {
                    name: "countryId",
                    type: "Int",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                code2: {
                    name: "code2",
                    type: "String",
                    unique: true
                },
                code3: {
                    name: "code3",
                    type: "String",
                    unique: true
                },
                number: {
                    name: "number",
                    type: "Int"
                },
                name: {
                    name: "name",
                    type: "String"
                },
                description: {
                    name: "description",
                    type: "String"
                },
                addresses: {
                    name: "addresses",
                    type: "Address",
                    array: true,
                    relation: { opposite: "country" }
                },
                regions: {
                    name: "regions",
                    type: "AddressRegion",
                    array: true,
                    relation: { opposite: "country" }
                }
            },
            idFields: ["countryId"],
            uniqueFields: {
                countryId: { type: "Int" },
                code2: { type: "String" },
                code3: { type: "String" }
            }
        },
        AddressRegion: {
            name: "AddressRegion",
            fields: {
                regionId: {
                    name: "regionId",
                    type: "Int",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                isoCountryId: {
                    name: "isoCountryId",
                    type: "Int",
                    foreignKeyFor: [
                        "country"
                    ]
                },
                country: {
                    name: "country",
                    type: "ISOCountry",
                    relation: { opposite: "regions", fields: ["isoCountryId"], references: ["countryId"] }
                },
                name: {
                    name: "name",
                    type: "String"
                }
            },
            idFields: ["regionId"],
            uniqueFields: {
                regionId: { type: "Int" }
            }
        },
        Address: {
            name: "Address",
            fields: {
                addressID: {
                    name: "addressID",
                    type: "Int",
                    id: true,
                    default: ExpressionUtils.call("autoincrement")
                },
                buildingCode: {
                    name: "buildingCode",
                    type: "String",
                    optional: true
                },
                room: {
                    name: "room",
                    type: "String",
                    optional: true
                },
                careOf: {
                    name: "careOf",
                    type: "String",
                    optional: true
                },
                street2: {
                    name: "street2",
                    type: "String",
                    optional: true
                },
                street3: {
                    name: "street3",
                    type: "String",
                    optional: true
                },
                houseNumber: {
                    name: "houseNumber",
                    type: "Int",
                    optional: true
                },
                street: {
                    name: "street",
                    type: "String"
                },
                town: {
                    name: "town",
                    type: "String",
                    optional: true
                },
                county: {
                    name: "county",
                    type: "String",
                    optional: true
                },
                postCode: {
                    name: "postCode",
                    type: "String",
                    optional: true
                },
                isoCountryId: {
                    name: "isoCountryId",
                    type: "Int",
                    foreignKeyFor: [
                        "country"
                    ]
                },
                country: {
                    name: "country",
                    type: "ISOCountry",
                    relation: { opposite: "addresses", fields: ["isoCountryId"], references: ["countryId"] }
                }
            },
            idFields: ["addressID"],
            uniqueFields: {
                addressID: { type: "Int" }
            }
        },
        Apikey: {
            name: "Apikey",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true
                },
                name: {
                    name: "name",
                    type: "String",
                    optional: true
                },
                start: {
                    name: "start",
                    type: "String",
                    optional: true
                },
                prefix: {
                    name: "prefix",
                    type: "String",
                    optional: true
                },
                key: {
                    name: "key",
                    type: "String"
                },
                userId: {
                    name: "userId",
                    type: "String",
                    unique: true,
                    foreignKeyFor: [
                        "user"
                    ]
                },
                user: {
                    name: "user",
                    type: "User",
                    relation: { opposite: "apiKey", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                },
                refillInterval: {
                    name: "refillInterval",
                    type: "Int",
                    optional: true
                },
                refillAmount: {
                    name: "refillAmount",
                    type: "Int",
                    optional: true
                },
                lastRefillAt: {
                    name: "lastRefillAt",
                    type: "DateTime",
                    optional: true
                },
                enabled: {
                    name: "enabled",
                    type: "Boolean",
                    optional: true,
                    default: true
                },
                rateLimitEnabled: {
                    name: "rateLimitEnabled",
                    type: "Boolean",
                    optional: true,
                    default: true
                },
                rateLimitTimeWindow: {
                    name: "rateLimitTimeWindow",
                    type: "Int",
                    optional: true
                },
                rateLimitMax: {
                    name: "rateLimitMax",
                    type: "Int",
                    optional: true
                },
                requestCount: {
                    name: "requestCount",
                    type: "Int",
                    optional: true
                },
                remaining: {
                    name: "remaining",
                    type: "Int",
                    optional: true
                },
                lastRequest: {
                    name: "lastRequest",
                    type: "DateTime",
                    optional: true
                },
                expiresAt: {
                    name: "expiresAt",
                    type: "DateTime",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime"
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime"
                },
                permissions: {
                    name: "permissions",
                    type: "String",
                    optional: true
                },
                metadata: {
                    name: "metadata",
                    type: "String",
                    optional: true
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                userId: { type: "String" }
            }
        }
    } as const;
    typeDefs = {
        Auth: {
            name: "Auth",
            fields: {
                userId: {
                    name: "userId",
                    type: "String"
                },
                organizationId: {
                    name: "organizationId",
                    type: "String",
                    optional: true
                },
                organizationRole: {
                    name: "organizationRole",
                    type: "String",
                    optional: true
                }
            },
            attributes: [
                { name: "@@auth" }
            ]
        }
    } as const;
    authType = "Auth" as const;
    plugins = {};
}
export const schema = new SchemaType();
