//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, ExpressionUtils } from "@zenstackhq/orm/schema";
export class SchemaType implements SchemaDef {
    provider = {
        type: "postgresql",
        defaultSchema: "charitatis"
    } as const;
    models = {
        TodoList: {
            name: "TodoList",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }],
                    default: ExpressionUtils.call("cuid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }]
                },
                name: {
                    name: "name",
                    type: "String"
                },
                owner: {
                    name: "owner",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array([ExpressionUtils.field("ownerId")]) }, { name: "references", value: ExpressionUtils.array([ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "todoLists", fields: ["ownerId"], references: ["id"], onDelete: "Cascade", hasDefault: true }
                },
                ownerId: {
                    name: "ownerId",
                    type: "String",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.member(ExpressionUtils.call("auth"), ["userId"]) }] }],
                    default: ExpressionUtils.member(ExpressionUtils.call("auth"), ["userId"]),
                    foreignKeyFor: [
                        "owner"
                    ]
                },
                organization: {
                    name: "organization",
                    type: "Organization",
                    optional: true,
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array([ExpressionUtils.field("organizationId")]) }, { name: "references", value: ExpressionUtils.array([ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "todoLists", fields: ["organizationId"], references: ["id"], onDelete: "Cascade", hasDefault: true }
                },
                organizationId: {
                    name: "organizationId",
                    type: "String",
                    optional: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.member(ExpressionUtils.call("auth"), ["organizationId"]) }] }],
                    default: ExpressionUtils.member(ExpressionUtils.call("auth"), ["organizationId"]),
                    foreignKeyFor: [
                        "organization"
                    ]
                },
                todos: {
                    name: "todos",
                    type: "Todo",
                    array: true,
                    relation: { opposite: "list" }
                }
            },
            attributes: [
                { name: "@@deny", args: [{ name: "operation", value: ExpressionUtils.literal("all") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.call("auth"), "==", ExpressionUtils._null()) }] },
                { name: "@@deny", args: [{ name: "operation", value: ExpressionUtils.literal("all") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.member(ExpressionUtils.call("auth"), ["organizationId"]), "!=", ExpressionUtils.field("organizationId")) }] },
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("create") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.member(ExpressionUtils.call("auth"), ["userId"]), "==", ExpressionUtils.field("ownerId")) }] },
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("all") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.member(ExpressionUtils.call("auth"), ["userId"]), "==", ExpressionUtils.field("ownerId")), "||", ExpressionUtils.binary(ExpressionUtils.member(ExpressionUtils.call("auth"), ["organizationRole"]), "==", ExpressionUtils.literal("owner"))), "||", ExpressionUtils.binary(ExpressionUtils.member(ExpressionUtils.call("auth"), ["organizationRole"]), "==", ExpressionUtils.literal("admin"))) }] },
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("read") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.field("organizationId"), "!=", ExpressionUtils._null()) }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Todo: {
            name: "Todo",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }],
                    default: ExpressionUtils.call("cuid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }]
                },
                title: {
                    name: "title",
                    type: "String"
                },
                done: {
                    name: "done",
                    type: "Boolean",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }],
                    default: false
                },
                listId: {
                    name: "listId",
                    type: "String",
                    foreignKeyFor: [
                        "list"
                    ]
                },
                list: {
                    name: "list",
                    type: "TodoList",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array([ExpressionUtils.field("listId")]) }, { name: "references", value: ExpressionUtils.array([ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "todos", fields: ["listId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            attributes: [
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("all") }, { name: "condition", value: ExpressionUtils.call("check", [ExpressionUtils.field("list"), ExpressionUtils.literal("read")]) }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        User: {
            name: "User",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }],
                    default: ExpressionUtils.call("cuid")
                },
                name: {
                    name: "name",
                    type: "String",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("") }] }],
                    default: ""
                },
                displayName: {
                    name: "displayName",
                    type: "String",
                    attributes: [{ name: "@length", args: [{ name: "min", value: ExpressionUtils.literal(1) }, { name: "max", value: ExpressionUtils.literal(40) }, { name: "message", value: ExpressionUtils.literal("Display name is required up to 40 characters") }] }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("") }] }],
                    default: ""
                },
                firstName: {
                    name: "firstName",
                    type: "String",
                    attributes: [{ name: "@length", args: [{ name: "min", value: ExpressionUtils.literal(1) }, { name: "max", value: ExpressionUtils.literal(40) }, { name: "message", value: ExpressionUtils.literal("First name is required up to 40 characters") }] }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("") }] }],
                    default: ""
                },
                familyName: {
                    name: "familyName",
                    type: "String",
                    attributes: [{ name: "@length", args: [{ name: "min", value: ExpressionUtils.literal(1) }, { name: "max", value: ExpressionUtils.literal(40) }, { name: "message", value: ExpressionUtils.literal("Family name is required up to 40 characters") }] }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("") }] }],
                    default: ""
                },
                email: {
                    name: "email",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }]
                },
                emailVerified: {
                    name: "emailVerified",
                    type: "Boolean",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }],
                    default: false
                },
                image: {
                    name: "image",
                    type: "String",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@updatedAt" }],
                    default: ExpressionUtils.call("now")
                },
                role: {
                    name: "role",
                    type: "String",
                    optional: true
                },
                banned: {
                    name: "banned",
                    type: "Boolean",
                    optional: true
                },
                banReason: {
                    name: "banReason",
                    type: "String",
                    optional: true
                },
                banExpires: {
                    name: "banExpires",
                    type: "DateTime",
                    optional: true
                },
                sessions: {
                    name: "sessions",
                    type: "Session",
                    array: true,
                    relation: { opposite: "user" }
                },
                accounts: {
                    name: "accounts",
                    type: "Account",
                    array: true,
                    relation: { opposite: "user" }
                },
                members: {
                    name: "members",
                    type: "Member",
                    array: true,
                    relation: { opposite: "user" }
                },
                teamMembers: {
                    name: "teamMembers",
                    type: "TeamMember",
                    array: true,
                    relation: { opposite: "user" }
                },
                invitations: {
                    name: "invitations",
                    type: "Invitation",
                    array: true,
                    relation: { opposite: "user" }
                },
                todoLists: {
                    name: "todoLists",
                    type: "TodoList",
                    array: true,
                    relation: { opposite: "owner" }
                },
                apiKey: {
                    name: "apiKey",
                    type: "Apikey",
                    optional: true,
                    relation: { opposite: "user" }
                },
                glaccounts: {
                    name: "glaccounts",
                    type: "GlAccount",
                    array: true,
                    relation: { opposite: "createdBy" }
                },
                partners: {
                    name: "partners",
                    type: "Partner",
                    array: true,
                    relation: { opposite: "createdBy" }
                },
                lastLoginMethod: {
                    name: "lastLoginMethod",
                    type: "String",
                    optional: true
                }
            },
            attributes: [
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("user") }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                email: { type: "String" }
            }
        },
        Account: {
            name: "Account",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }]
                },
                accountId: {
                    name: "accountId",
                    type: "String"
                },
                providerId: {
                    name: "providerId",
                    type: "String"
                },
                userId: {
                    name: "userId",
                    type: "String",
                    foreignKeyFor: [
                        "user"
                    ]
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array([ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array([ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "accounts", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                },
                accessToken: {
                    name: "accessToken",
                    type: "String",
                    optional: true
                },
                refreshToken: {
                    name: "refreshToken",
                    type: "String",
                    optional: true
                },
                idToken: {
                    name: "idToken",
                    type: "String",
                    optional: true
                },
                accessTokenExpiresAt: {
                    name: "accessTokenExpiresAt",
                    type: "DateTime",
                    optional: true
                },
                refreshTokenExpiresAt: {
                    name: "refreshTokenExpiresAt",
                    type: "DateTime",
                    optional: true
                },
                scope: {
                    name: "scope",
                    type: "String",
                    optional: true
                },
                password: {
                    name: "password",
                    type: "String",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }]
                }
            },
            attributes: [
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("account") }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Verification: {
            name: "Verification",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }]
                },
                identifier: {
                    name: "identifier",
                    type: "String"
                },
                value: {
                    name: "value",
                    type: "String"
                },
                expiresAt: {
                    name: "expiresAt",
                    type: "DateTime"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    optional: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    optional: true,
                    updatedAt: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@updatedAt" }],
                    default: ExpressionUtils.call("now")
                }
            },
            attributes: [
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("verification") }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Organization: {
            name: "Organization",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }]
                },
                name: {
                    name: "name",
                    type: "String"
                },
                slug: {
                    name: "slug",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }]
                },
                logo: {
                    name: "logo",
                    type: "String",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime"
                },
                metadata: {
                    name: "metadata",
                    type: "String",
                    optional: true
                },
                tradingName: {
                    name: "tradingName",
                    type: "String",
                    attributes: [{ name: "@length", args: [{ name: "min", value: ExpressionUtils.literal(1) }, { name: "max", value: ExpressionUtils.literal(50) }, { name: "message", value: ExpressionUtils.literal("Must be between 1 and 50 characters") }] }]
                },
                legalForm: {
                    name: "legalForm",
                    type: "OrgLegalForm",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("SoleTrader") }] }],
                    default: "SoleTrader"
                },
                legalName: {
                    name: "legalName",
                    type: "String",
                    attributes: [{ name: "@length", args: [{ name: "min", value: ExpressionUtils.literal(1) }, { name: "max", value: ExpressionUtils.literal(50) }, { name: "message", value: ExpressionUtils.literal("Must be between 1 and 50 characters") }] }]
                },
                charityNumber: {
                    name: "charityNumber",
                    type: "String",
                    optional: true
                },
                taxRef: {
                    name: "taxRef",
                    type: "String",
                    optional: true
                },
                companyNumber: {
                    name: "companyNumber",
                    type: "String",
                    optional: true
                },
                companyName: {
                    name: "companyName",
                    type: "String",
                    optional: true
                },
                idType: {
                    name: "idType",
                    type: "OrgIdentificationType",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("UTR_tax_ref") }] }],
                    default: "UTR_tax_ref"
                },
                identification: {
                    name: "identification",
                    type: "String",
                    attributes: [{ name: "@length", args: [{ name: "min", value: ExpressionUtils.literal(1) }, { name: "max", value: ExpressionUtils.literal(50) }, { name: "message", value: ExpressionUtils.literal("Must be between 1 and 50 characters") }] }]
                },
                accountType: {
                    name: "accountType",
                    type: "OrgPlanType",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("Trial") }] }],
                    default: "Trial"
                },
                members: {
                    name: "members",
                    type: "Member",
                    array: true,
                    relation: { opposite: "organization" }
                },
                invitations: {
                    name: "invitations",
                    type: "Invitation",
                    array: true,
                    relation: { opposite: "organization" }
                },
                todoLists: {
                    name: "todoLists",
                    type: "TodoList",
                    array: true,
                    relation: { opposite: "organization" }
                }
            },
            attributes: [
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("organization") }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                slug: { type: "String" }
            }
        },
        Team: {
            name: "Team",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }]
                },
                name: {
                    name: "name",
                    type: "String"
                },
                organizationId: {
                    name: "organizationId",
                    type: "String"
                },
                teamMembers: {
                    name: "teamMembers",
                    type: "TeamMember",
                    array: true,
                    relation: { opposite: "team" }
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@updatedAt" }],
                    default: ExpressionUtils.call("now")
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Member: {
            name: "Member",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }]
                },
                organizationId: {
                    name: "organizationId",
                    type: "String",
                    foreignKeyFor: [
                        "organization"
                    ]
                },
                organization: {
                    name: "organization",
                    type: "Organization",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array([ExpressionUtils.field("organizationId")]) }, { name: "references", value: ExpressionUtils.array([ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "members", fields: ["organizationId"], references: ["id"], onDelete: "Cascade" }
                },
                userId: {
                    name: "userId",
                    type: "String",
                    foreignKeyFor: [
                        "user"
                    ]
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array([ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array([ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "members", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                },
                role: {
                    name: "role",
                    type: "String"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                updatesAt: {
                    name: "updatesAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@updatedAt" }],
                    default: ExpressionUtils.call("now")
                }
            },
            attributes: [
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("member") }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        TeamMember: {
            name: "TeamMember",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }]
                },
                teamId: {
                    name: "teamId",
                    type: "String",
                    foreignKeyFor: [
                        "team"
                    ]
                },
                team: {
                    name: "team",
                    type: "Team",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array([ExpressionUtils.field("teamId")]) }, { name: "references", value: ExpressionUtils.array([ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "teamMembers", fields: ["teamId"], references: ["id"], onDelete: "Cascade" }
                },
                userId: {
                    name: "userId",
                    type: "String",
                    foreignKeyFor: [
                        "user"
                    ]
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array([ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array([ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "teamMembers", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                updatesAt: {
                    name: "updatesAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@updatedAt" }],
                    default: ExpressionUtils.call("now")
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Invitation: {
            name: "Invitation",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }]
                },
                organizationId: {
                    name: "organizationId",
                    type: "String",
                    foreignKeyFor: [
                        "organization"
                    ]
                },
                organization: {
                    name: "organization",
                    type: "Organization",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array([ExpressionUtils.field("organizationId")]) }, { name: "references", value: ExpressionUtils.array([ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "invitations", fields: ["organizationId"], references: ["id"], onDelete: "Cascade" }
                },
                email: {
                    name: "email",
                    type: "String",
                    attributes: [{ name: "@email" }]
                },
                role: {
                    name: "role",
                    type: "String",
                    optional: true
                },
                status: {
                    name: "status",
                    type: "String"
                },
                expiresAt: {
                    name: "expiresAt",
                    type: "DateTime"
                },
                inviterId: {
                    name: "inviterId",
                    type: "String",
                    foreignKeyFor: [
                        "user"
                    ]
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array([ExpressionUtils.field("inviterId")]) }, { name: "references", value: ExpressionUtils.array([ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "invitations", fields: ["inviterId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            attributes: [
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("invitation") }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Session: {
            name: "Session",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }]
                },
                expiresAt: {
                    name: "expiresAt",
                    type: "DateTime"
                },
                token: {
                    name: "token",
                    type: "String"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime"
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime"
                },
                ipAddress: {
                    name: "ipAddress",
                    type: "String",
                    optional: true
                },
                userAgent: {
                    name: "userAgent",
                    type: "String",
                    optional: true
                },
                userId: {
                    name: "userId",
                    type: "String",
                    foreignKeyFor: [
                        "user"
                    ]
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array([ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array([ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "sessions", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                },
                activeOrganizationId: {
                    name: "activeOrganizationId",
                    type: "String",
                    optional: true
                },
                impersonatedBy: {
                    name: "impersonatedBy",
                    type: "String",
                    optional: true
                }
            },
            attributes: [
                { name: "@@unique", args: [{ name: "fields", value: ExpressionUtils.array([ExpressionUtils.field("token")]) }] },
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("session") }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                token: { type: "String" }
            }
        },
        ISOCountry: {
            name: "ISOCountry",
            fields: {
                countryId: {
                    name: "countryId",
                    type: "Int",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("autoincrement") }] }],
                    default: ExpressionUtils.call("autoincrement")
                },
                code2: {
                    name: "code2",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }, { name: "@length", args: [{ name: "min", value: ExpressionUtils.literal(1) }, { name: "max", value: ExpressionUtils.literal(2) }, { name: "message", value: ExpressionUtils.literal("Code must be length 2 char") }] }]
                },
                code3: {
                    name: "code3",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }, { name: "@length", args: [{ name: "min", value: ExpressionUtils.literal(1) }, { name: "max", value: ExpressionUtils.literal(3) }, { name: "message", value: ExpressionUtils.literal("ISO address code3 must be 3 char length ") }] }]
                },
                number: {
                    name: "number",
                    type: "Int"
                },
                name: {
                    name: "name",
                    type: "String"
                },
                description: {
                    name: "description",
                    type: "String"
                },
                addresses: {
                    name: "addresses",
                    type: "Address",
                    array: true,
                    relation: { opposite: "country" }
                },
                regions: {
                    name: "regions",
                    type: "AddressRegion",
                    array: true,
                    relation: { opposite: "country" }
                }
            },
            idFields: ["countryId"],
            uniqueFields: {
                countryId: { type: "Int" },
                code2: { type: "String" },
                code3: { type: "String" }
            }
        },
        AddressRegion: {
            name: "AddressRegion",
            fields: {
                regionId: {
                    name: "regionId",
                    type: "Int",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("autoincrement") }] }],
                    default: ExpressionUtils.call("autoincrement")
                },
                isoCountryId: {
                    name: "isoCountryId",
                    type: "Int",
                    foreignKeyFor: [
                        "country"
                    ]
                },
                country: {
                    name: "country",
                    type: "ISOCountry",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array([ExpressionUtils.field("isoCountryId")]) }, { name: "references", value: ExpressionUtils.array([ExpressionUtils.field("countryId")]) }] }],
                    relation: { opposite: "regions", fields: ["isoCountryId"], references: ["countryId"] }
                },
                name: {
                    name: "name",
                    type: "String"
                }
            },
            idFields: ["regionId"],
            uniqueFields: {
                regionId: { type: "Int" }
            }
        },
        Address: {
            name: "Address",
            fields: {
                addressID: {
                    name: "addressID",
                    type: "Int",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("autoincrement") }] }],
                    default: ExpressionUtils.call("autoincrement")
                },
                buildingCode: {
                    name: "buildingCode",
                    type: "String",
                    optional: true,
                    attributes: [{ name: "@length", args: [{ name: "min", value: ExpressionUtils.literal(0) }, { name: "max", value: ExpressionUtils.literal(10) }, { name: "message", value: ExpressionUtils.literal("building code can be up 10 characters") }] }]
                },
                room: {
                    name: "room",
                    type: "String",
                    optional: true,
                    attributes: [{ name: "@length", args: [{ name: "min", value: ExpressionUtils.literal(0) }, { name: "max", value: ExpressionUtils.literal(10) }, { name: "message", value: ExpressionUtils.literal("room can be up 10 characters") }] }]
                },
                careOf: {
                    name: "careOf",
                    type: "String",
                    optional: true,
                    attributes: [{ name: "@length", args: [{ name: "min", value: ExpressionUtils.literal(0) }, { name: "max", value: ExpressionUtils.literal(50) }, { name: "message", value: ExpressionUtils.literal("Care of be up 10 characters") }] }]
                },
                street2: {
                    name: "street2",
                    type: "String",
                    optional: true,
                    attributes: [{ name: "@length", args: [{ name: "min", value: ExpressionUtils.literal(0) }, { name: "max", value: ExpressionUtils.literal(50) }, { name: "message", value: ExpressionUtils.literal("Street2 can be up 10 characters") }] }]
                },
                street3: {
                    name: "street3",
                    type: "String",
                    optional: true,
                    attributes: [{ name: "@length", args: [{ name: "min", value: ExpressionUtils.literal(0) }, { name: "max", value: ExpressionUtils.literal(50) }, { name: "message", value: ExpressionUtils.literal("Street3 can be up 10 characters") }] }]
                },
                houseNumber: {
                    name: "houseNumber",
                    type: "Int",
                    optional: true
                },
                street: {
                    name: "street",
                    type: "String",
                    attributes: [{ name: "@length", args: [{ name: "min", value: ExpressionUtils.literal(1) }, { name: "max", value: ExpressionUtils.literal(50) }, { name: "message", value: ExpressionUtils.literal("Street must be upto 50 char") }] }]
                },
                town: {
                    name: "town",
                    type: "String",
                    optional: true,
                    attributes: [{ name: "@length", args: [{ name: "min", value: ExpressionUtils.literal(0) }, { name: "max", value: ExpressionUtils.literal(50) }, { name: "message", value: ExpressionUtils.literal("Town can be up 10 characters") }] }]
                },
                county: {
                    name: "county",
                    type: "String",
                    optional: true,
                    attributes: [{ name: "@length", args: [{ name: "min", value: ExpressionUtils.literal(0) }, { name: "max", value: ExpressionUtils.literal(50) }, { name: "message", value: ExpressionUtils.literal("County can be up 10 characters") }] }]
                },
                postCode: {
                    name: "postCode",
                    type: "String",
                    optional: true,
                    attributes: [{ name: "@length", args: [{ name: "min", value: ExpressionUtils.literal(1) }, { name: "max", value: ExpressionUtils.literal(10) }, { name: "message", value: ExpressionUtils.literal("Post code must be up 10 characters") }] }]
                },
                isoCountryId: {
                    name: "isoCountryId",
                    type: "Int",
                    foreignKeyFor: [
                        "country"
                    ]
                },
                country: {
                    name: "country",
                    type: "ISOCountry",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array([ExpressionUtils.field("isoCountryId")]) }, { name: "references", value: ExpressionUtils.array([ExpressionUtils.field("countryId")]) }] }],
                    relation: { opposite: "addresses", fields: ["isoCountryId"], references: ["countryId"] }
                },
                partnerId: {
                    name: "partnerId",
                    type: "String"
                },
                partners: {
                    name: "partners",
                    type: "Partner",
                    array: true,
                    relation: { opposite: "address" }
                }
            },
            idFields: ["addressID"],
            uniqueFields: {
                addressID: { type: "Int" }
            }
        },
        Apikey: {
            name: "Apikey",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }]
                },
                name: {
                    name: "name",
                    type: "String",
                    optional: true
                },
                start: {
                    name: "start",
                    type: "String",
                    optional: true
                },
                prefix: {
                    name: "prefix",
                    type: "String",
                    optional: true
                },
                key: {
                    name: "key",
                    type: "String"
                },
                userId: {
                    name: "userId",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }],
                    foreignKeyFor: [
                        "user"
                    ]
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array([ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array([ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "apiKey", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                },
                refillInterval: {
                    name: "refillInterval",
                    type: "Int",
                    optional: true
                },
                refillAmount: {
                    name: "refillAmount",
                    type: "Int",
                    optional: true
                },
                lastRefillAt: {
                    name: "lastRefillAt",
                    type: "DateTime",
                    optional: true
                },
                enabled: {
                    name: "enabled",
                    type: "Boolean",
                    optional: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(true) }] }],
                    default: true
                },
                rateLimitEnabled: {
                    name: "rateLimitEnabled",
                    type: "Boolean",
                    optional: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(true) }] }],
                    default: true
                },
                rateLimitTimeWindow: {
                    name: "rateLimitTimeWindow",
                    type: "Int",
                    optional: true
                },
                rateLimitMax: {
                    name: "rateLimitMax",
                    type: "Int",
                    optional: true
                },
                requestCount: {
                    name: "requestCount",
                    type: "Int",
                    optional: true
                },
                remaining: {
                    name: "remaining",
                    type: "Int",
                    optional: true
                },
                lastRequest: {
                    name: "lastRequest",
                    type: "DateTime",
                    optional: true
                },
                expiresAt: {
                    name: "expiresAt",
                    type: "DateTime",
                    optional: true
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime"
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime"
                },
                permissions: {
                    name: "permissions",
                    type: "String",
                    optional: true
                },
                metadata: {
                    name: "metadata",
                    type: "String",
                    optional: true
                }
            },
            attributes: [
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("apikey") }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                userId: { type: "String" }
            }
        },
        GlAccount: {
            name: "GlAccount",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }],
                    default: ExpressionUtils.call("uuid")
                },
                name: {
                    name: "name",
                    type: "String"
                },
                balanceSheet: {
                    name: "balanceSheet",
                    type: "Boolean"
                },
                reportCat: {
                    name: "reportCat",
                    type: "String"
                },
                createdById: {
                    name: "createdById",
                    type: "String",
                    foreignKeyFor: [
                        "createdBy"
                    ]
                },
                createdBy: {
                    name: "createdBy",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array([ExpressionUtils.field("createdById")]) }, { name: "references", value: ExpressionUtils.array([ExpressionUtils.field("id")]) }] }],
                    relation: { opposite: "glaccounts", fields: ["createdById"], references: ["id"] }
                },
                ArApRecAccount: {
                    name: "ArApRecAccount",
                    type: "ArAPPartner",
                    array: true,
                    relation: { opposite: "reconAccount" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Partner: {
            name: "Partner",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }],
                    default: ExpressionUtils.call("uuid")
                },
                name: {
                    name: "name",
                    type: "String",
                    attributes: [{ name: "@length", args: [{ name: "min", value: ExpressionUtils.literal(1) }, { name: "max", value: ExpressionUtils.literal(40) }, { name: "message", value: ExpressionUtils.literal("Partner name is requiredd") }] }]
                },
                personType: {
                    name: "personType",
                    type: "PersonType"
                },
                familyName: {
                    name: "familyName",
                    type: "String",
                    optional: true
                },
                addressId: {
                    name: "addressId",
                    type: "Int",
                    foreignKeyFor: [
                        "address"
                    ]
                },
                searchTerm: {
                    name: "searchTerm",
                    type: "String",
                    attributes: [{ name: "@length", args: [{ name: "min", value: ExpressionUtils.literal(1) }, { name: "max", value: ExpressionUtils.literal(20) }, { name: "message", value: ExpressionUtils.literal("Search term to find partners") }] }]
                },
                stripeId: {
                    name: "stripeId",
                    type: "String"
                },
                address: {
                    name: "address",
                    type: "Address",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array([ExpressionUtils.field("addressId")]) }, { name: "references", value: ExpressionUtils.array([ExpressionUtils.field("addressID")]) }] }],
                    relation: { opposite: "partners", fields: ["addressId"], references: ["addressID"] }
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@updatedAt" }],
                    default: ExpressionUtils.call("now")
                },
                createdById: {
                    name: "createdById",
                    type: "String",
                    foreignKeyFor: [
                        "createdBy"
                    ]
                },
                createdBy: {
                    name: "createdBy",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array([ExpressionUtils.field("createdById")]) }, { name: "references", value: ExpressionUtils.array([ExpressionUtils.field("id")]) }] }],
                    relation: { opposite: "partners", fields: ["createdById"], references: ["id"] }
                },
                type: {
                    name: "type",
                    type: "String",
                    isDiscriminator: true,
                    attributes: [{ name: "@length", args: [{ name: "min", value: ExpressionUtils.literal(1) }, { name: "max", value: ExpressionUtils.literal(20) }, { name: "message", value: ExpressionUtils.literal("Type of partner") }] }]
                }
            },
            attributes: [
                { name: "@@delegate", args: [{ name: "discriminator", value: ExpressionUtils.field("type") }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            },
            isDelegate: true,
            subModels: ["ArAPPartner"]
        },
        ArAPPartner: {
            name: "ArAPPartner",
            baseModel: "Partner",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }],
                    default: ExpressionUtils.call("uuid")
                },
                name: {
                    name: "name",
                    type: "String",
                    originModel: "Partner",
                    attributes: [{ name: "@length", args: [{ name: "min", value: ExpressionUtils.literal(1) }, { name: "max", value: ExpressionUtils.literal(40) }, { name: "message", value: ExpressionUtils.literal("Partner name is requiredd") }] }]
                },
                personType: {
                    name: "personType",
                    type: "PersonType",
                    originModel: "Partner"
                },
                familyName: {
                    name: "familyName",
                    type: "String",
                    optional: true,
                    originModel: "Partner"
                },
                addressId: {
                    name: "addressId",
                    type: "Int",
                    originModel: "Partner",
                    foreignKeyFor: [
                        "address"
                    ]
                },
                searchTerm: {
                    name: "searchTerm",
                    type: "String",
                    originModel: "Partner",
                    attributes: [{ name: "@length", args: [{ name: "min", value: ExpressionUtils.literal(1) }, { name: "max", value: ExpressionUtils.literal(20) }, { name: "message", value: ExpressionUtils.literal("Search term to find partners") }] }]
                },
                stripeId: {
                    name: "stripeId",
                    type: "String",
                    originModel: "Partner"
                },
                address: {
                    name: "address",
                    type: "Address",
                    originModel: "Partner",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array([ExpressionUtils.field("addressId")]) }, { name: "references", value: ExpressionUtils.array([ExpressionUtils.field("addressID")]) }] }],
                    relation: { opposite: "partners", fields: ["addressId"], references: ["addressID"] }
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    originModel: "Partner",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    originModel: "Partner",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@updatedAt" }],
                    default: ExpressionUtils.call("now")
                },
                createdById: {
                    name: "createdById",
                    type: "String",
                    originModel: "Partner",
                    foreignKeyFor: [
                        "createdBy"
                    ]
                },
                createdBy: {
                    name: "createdBy",
                    type: "User",
                    originModel: "Partner",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array([ExpressionUtils.field("createdById")]) }, { name: "references", value: ExpressionUtils.array([ExpressionUtils.field("id")]) }] }],
                    relation: { opposite: "partners", fields: ["createdById"], references: ["id"] }
                },
                type: {
                    name: "type",
                    type: "String",
                    originModel: "Partner",
                    isDiscriminator: true,
                    attributes: [{ name: "@length", args: [{ name: "min", value: ExpressionUtils.literal(1) }, { name: "max", value: ExpressionUtils.literal(20) }, { name: "message", value: ExpressionUtils.literal("Type of partner") }] }]
                },
                reconAccountId: {
                    name: "reconAccountId",
                    type: "String",
                    foreignKeyFor: [
                        "reconAccount"
                    ]
                },
                reconAccount: {
                    name: "reconAccount",
                    type: "GlAccount",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array([ExpressionUtils.field("reconAccountId")]) }, { name: "references", value: ExpressionUtils.array([ExpressionUtils.field("id")]) }] }],
                    relation: { opposite: "ArApRecAccount", fields: ["reconAccountId"], references: ["id"] }
                },
                companyId: {
                    name: "companyId",
                    type: "String"
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        FiscalYearVariant: {
            name: "FiscalYearVariant",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("autoincrement") }] }],
                    default: ExpressionUtils.call("autoincrement")
                },
                name: {
                    name: "name",
                    type: "String"
                },
                monthNum: {
                    name: "monthNum",
                    type: "Int"
                },
                day: {
                    name: "day",
                    type: "Int"
                },
                fiscPeriod: {
                    name: "fiscPeriod",
                    type: "Int"
                },
                yearShift: {
                    name: "yearShift",
                    type: "Boolean"
                }
            },
            attributes: [
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("create,read") }, { name: "condition", value: ExpressionUtils.literal(true) }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" }
            }
        },
        PostingPeriod: {
            name: "PostingPeriod",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("autoincrement") }] }],
                    default: ExpressionUtils.call("autoincrement")
                },
                year: {
                    name: "year",
                    type: "Int"
                },
                period: {
                    name: "period",
                    type: "Int"
                },
                open: {
                    name: "open",
                    type: "Boolean"
                },
                companyId: {
                    name: "companyId",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }]
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" },
                companyId: { type: "String" }
            }
        },
        Parameter: {
            name: "Parameter",
            fields: {
                id: {
                    name: "id",
                    type: "Int",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("autoincrement") }] }],
                    default: ExpressionUtils.call("autoincrement")
                },
                name: {
                    name: "name",
                    type: "String"
                },
                value: {
                    name: "value",
                    type: "String"
                }
            },
            attributes: [
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("create,read") }, { name: "condition", value: ExpressionUtils.literal(true) }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "Int" }
            }
        }
    } as const;
    typeDefs = {
        Auth: {
            name: "Auth",
            fields: {
                userId: {
                    name: "userId",
                    type: "String",
                    attributes: [{ name: "@id" }]
                },
                organizationId: {
                    name: "organizationId",
                    type: "String",
                    optional: true
                },
                organizationRole: {
                    name: "organizationRole",
                    type: "String",
                    optional: true
                },
                role: {
                    name: "role",
                    type: "String"
                }
            },
            attributes: [
                { name: "@@auth" }
            ]
        }
    } as const;
    enums = {
        OrgLegalForm: {
            values: {
                SoleTrader: "SoleTrader",
                Company: "Company",
                Partnership: "Partnership"
            }
        },
        OrgIdentificationType: {
            values: {
                UTR_tax_ref: "UTR_tax_ref",
                Company_Number: "Company_Number",
                Charity_number: "Charity_number"
            }
        },
        OrgPlanType: {
            values: {
                Trial: "Trial",
                Free: "Free",
                Premium: "Premium"
            }
        },
        PersonType: {
            values: {
                Person: "Person",
                Organisation: "Organisation"
            }
        }
    } as const;
    authType = "Auth" as const;
    plugins = {};
}
export const schema = new SchemaType();
